"""Markdown rendering utilities for Phase 1 Reports (Context Pack)."""

from typing import Dict


def render_overview(context: Dict) -> str:
    project = context.get("project_name", "Unknown Project")
    summary = context.get("summary", "")
    lines = [f"# {project}", "", summary, ""]
    lines += ["## Purpose", "- This document provides an auditable context pack for downstream agents.", ""]
    return "\n".join(lines)


def render_stack(context: Dict) -> str:
    stack = context.get("stack", {})
    lines = ["## Stack", ""]
    lines.append("Languages: " + ", ".join(stack.get("languages", [])))
    lines.append("Frameworks: " + ", ".join(stack.get("frameworks", [])))
    lines.append("Databases: " + ", ".join(stack.get("databases", [])))
    lines.append("Infrastructure: " + ", ".join(stack.get("infrastructure", [])))
    lines.append("External services: " + ", ".join(stack.get("external_services", [])))
    lines.append("")
    return "\n".join(lines)


def render_components(context: Dict) -> str:
    components = context.get("components", [])
    lines = ["## Components", ""]
    for c in components:
        name = c.get("name", "Unknown Component")
        t = c.get("type", "component")
        lines.append(f"- **{name}** ({t})")
    lines.append("")
    return "\n".join(lines)


def render_dependencies(context: Dict) -> str:
    deps = context.get("dependencies", [])
    lines = ["## Dependencies", ""]
    for d in deps:
        lines.append(f"- {d.get('name', '')} ({d.get('type','')})")
    lines.append("")
    return "\n".join(lines)


def render_flows(context: Dict) -> str:
    flows = context.get("flows", [])
    lines = ["## Flows", ""]
    for f in flows:
        lines.append(f"- {f.get('name','')} : {f.get('description','')} (from {f.get('source','')} to {f.get('target','')})")
    lines.append("")
    return "\n".join(lines)


def render_diagrams(context: Dict) -> str:
    # Placeholder: diagrams will be appended as Mermaid blocks in 08-diagrams.md
    return ""  # The actual Mermaid blocks are generated by mermaid_renderer


def render_all(context: Dict) -> Dict[str, str]:
    return {
        "01-overview.md": render_overview(context),
        "02-stack.md": render_stack(context),
        "03-components.md": render_components(context),
        "04-dependencies.md": render_dependencies(context),
        "05-flows.md": render_flows(context),
        "08-diagrams.md": render_diagrams(context),
    }
